### ISSUE TITLE
Find an alternative for rails-assets.org?

### ISSUE THREAD

**Issue by kinow** [MakersNZ/MakersMap#25]
Hi!

I'm not a Ruby developer, so apologies if I'm saying anything too dumb :-) 

I was following the development setup instructions in the project README, when the bundle command failed for not being able to connect to rails-assets. This issue has been happening for about 1 hour now, so I'm calling it a day and going to play with some other OSS project for now :-)

Googling, looks like the project is going to be shut down in 2016? source https://github.com/rails-assets/rails-assets/issues/291

Going in the browser I see an error page as follows.

![screenshot - 170116 - 16 46 49](https://cloud.githubusercontent.com/assets/304786/12375832/f598926a-bd39-11e5-9553-2ed4f9dd8c6c.png)

And here's the console output

```
vagrant@MakerMap-RoR-DevBox:/vagrant$ bundle install
Fetching source index from https://rails-assets.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rails-assets.org/
Could not fetch specs from https://rails-assets.org/
```

Are there any alternatives to rails-assets?

**Comment by dangerousbeans** [comment]
Ah yeah this looks totally offline for me too, damn! Rails assets was really great too.

I'll try and fix it up to not need rails assets, maybe with a bowerlife instead, shouldn't be too bad

**Comment by kinow** [comment]
I can try to help with bower, have used it in some other projects, though they were mostly PHP+Laravel5.

**Comment by dangerousbeans** [comment]
That's be great! I had a whack at it on this branch: https://github.com/MakersNZ/MakersMap/tree/bowerify

switching to bower-rails, but after installing it all it can't find bootstrap in the assets pipeline. You can get the page to load at least by removing the require lines from the top of application.coffee:

```

**Comment by dangerousbeans** [comment]
Fixed with: https://github.com/MakersNZ/MakersMap/compare/dca609e647fa...96b51efad1f0

Assets now handled with a Bowerfile DSL (similar to Gemfile)

Deploy to Heroku might be ropey, but fingers crossed

**Comment by kinow** [comment]
Confirming that resyncing the branch, starting vagrant again and trying bundle now works (#26 seems to have fixed the issue with nokogiri as well)

```
Installing railties 4.2.3
Installing sprockets-rails 2.3.3
Installing kaminari 0.14.1
Installing simple_form 3.2.0
Installing coffee-rails 4.1.0
Installing responders 2.1.0
Installing factory_girl_rails 4.5.0
Installing haml-rails 0.9.0
Installing jquery-rails 4.0.5
Installing quiet_assets 1.1.0
Installing rspec-rails 3.4.0
Installing rails 4.2.3
Installing sass-rails 5.0.4
Installing web-console 2.2.1
Installing turbolinks 2.5.3
Installing devise 3.5.2
Installing activerecord-postgres-earthdistance 0.4.3
Installing bootstrap-kaminari-views 0.0.5
Bundle complete! 40 Gemfile dependencies, 116 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
vagrant@MakerMap-RoR-DevBox:/vagrant$ 
```

**Comment by kinow** [comment]
Thanks!
